<a href="https://colab.research.google.com/github/gabrielalastra/PYTHON/blob/master/analysis_dadosExcel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

primeiro dia de intensivo de "python para mercado"

Passo 1: Importar base de dados

Passo 2: Calcular o faturamento de cada loja

Passo 3: Calcular a quantidade de produtos vendidos de cada loja

Passo 4: Calcular o ticket médio dos produtos vendidos de cada loja

Passo 5: Enviar email para diretoria

Passo 6 Enviar email para cada loja

In [ ]:
#para integrar o excel
import pandas as pd
#importar o arquivo
tabela_vendas = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/Vendas.xlsx")
#exibir
display(tabela_vendas)

        Código Venda       Data  ... Valor Unitário Valor Final
0                  1 2019-01-01  ...            358         358
1                  1 2019-01-01  ...            180         360
2                  1 2019-01-01  ...            368         368
3                  2 2019-01-02  ...            200         600
4                  2 2019-01-02  ...             71          71
...              ...        ...  ...            ...         ...
100994         69996 2019-12-26  ...            102         204
100995         69996 2019-12-26  ...            270        1080
100996         69996 2019-12-26  ...             87          87
100997         69997 2019-12-26  ...            108         108
100998         69997 2019-12-26  ...            133         266

[100999 rows x 7 columns]

In [ ]:
#olhando a tabela as colunas necessarias para o faturamento de cada loja
#as colunas ID LOJA e Valor Final

#filtrar as colunas e agrupar as lojas e somar os valores fim
tabela_faturamento = tabela_vendas[["ID Loja","Valor Final"]].groupby("ID Loja").sum("Valor Final")
#para por em ordem decrescente
tabela_faturamento = tabela_faturamento.sort_values(by="Valor Final", ascending=False)
display(tabela_faturamento)

In [ ]:
#quantidade de produtos vendidos em cada loja
tabela_vendas = tabela_vendas[["ID Loja", "Quantidade"]].groupby("ID Loja").sum("Quantidade")
display(tabela_vendas)

                                  Quantidade
ID Loja
Bourbon Shopping SP                     8863
Center Shopping Uberlândia              8627
Iguatemi Campinas                       8935
Iguatemi Esplanada                      8580
Norte Shopping                          9014
Novo Shopping Ribeirão Preto            8751
Palladium Shopping Curitiba             9091
Parque Dom Pedro Shopping               8388
Passei das Águas Shopping               8618
Ribeirão Shopping                       8825
Rio Mar Recife                          8863
Rio Mar Shopping Fortaleza              8937
Salvador Shopping                       8698
Shopping Barra                          8638
Shopping Center Interlagos              8675
Shopping Center Leste Aricanduva        8938
Shopping Eldorado                       8719
Shopping Ibirapuera                     8723
Shopping Iguatemi Fortaleza             8629
Shopping Midway Mall                    8206
Shopping Morumbi                        8508
Shopping Recife                         8581
Shopping SP Market                      8927
Shopping União de Osasco                8730
Shopping Vila Velha                     9224